project_id = "mlkgvlgjocvrgxwqngnf"

[functions.chapa-payment]
verify_jwt = false

[functions.chapa-webhook]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-generate-description]
verify_jwt = false

[functions.ai-recommendations]
verify_jwt = false

[functions.ai-crop-disease]
verify_jwt = false

[functions.ai-price-suggestion]
verify_jwt = false

[functions.ai-market-trends]
verify_jwt = false

[functions.elevenlabs-scribe-token]
verify_jwt = false

[functions.ai-weather-advice]
verify_jwt = false